
FROM node:20 AS build
WORKDIR /app


COPY package.json package-lock.json tsconfig.json vite.config.ts ./


COPY src ./src
COPY *.html ./
COPY public ./public

RUN npm install
RUN npm run build


FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
